title: Automatic Detection of Aortic Valve Events Using Deep Neural Networks on Cardiac Signals from Epicardially Placed Accelerometer
description: Ali Wajdan, Tollef Struksnes Jahren, Manuel Villegas-Martinez, Faraz H Khan, Per Steinar Halvorsen, Hans Henrik Odland, Ole Jakob Elle, Anne H Schistad Solberg, Espen W Remme
